# Generated by Django 5.2.17 on 2026-08-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=16)),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_unread_ids', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='orchestrator.client')),
            ],
            options={
                'unique_together': {('client', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('gmail_thread_id', models.CharField(max_length=255)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='orchestrator.client')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='email_agent.emailaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
