# Generated by Django 5.2.17 on 2026-09-15 15:06

import apps.email_agent.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='access_token',
            field=apps.email_agent.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='refresh_token',
            field=apps.email_agent.fields.EncryptedTextField(),
        ),
    ]
